title:            Notariat Hansruedi Stadler
tagline:
description:
canonical: http://notariat.hansruedi-stadler.ch

# Owner/author information
owner:
  name:           Hansruedi Stadler
  bio:            "Rechtsanwalt und Notar"
  email:          stadler.hansruedi@bluewin.ch
  location:       "Altdorf, Uri, Schweiz"

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: Werdegang
    url: /about.html

defaults:
  -
    scope:
      path: ""
    values:
      layout: page


timezone:    Europe/Zurich
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

jekyll-press:
  exclude: 'atom.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
